# Generated by Django 3.1.4 on 2020-12-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
