# Generated by Django 3.1.4 on 2020-12-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_parsed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsed',
            name='id',
        ),
        migrations.AlterField(
            model_name='parsed',
            name='text',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
