# Generated by Django 3.1.4 on 2020-12-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_auto_20201218_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parsed',
        ),
    ]
